/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problema2;


import cuenta.*;
import tarjetas.*;
/**
 *
 * @author krypth
 */
public class Problema2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Problema2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        tdestandar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        destinoField = new javax.swing.JTextField();
        cantidadField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        coro = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cestandar = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        transButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tdjoven = new javax.swing.JRadioButton();
        cjoven = new javax.swing.JRadioButton();
        td10 = new javax.swing.JRadioButton();
        c10 = new javax.swing.JRadioButton();
        tdoro = new javax.swing.JRadioButton();
        tcoro = new javax.swing.JRadioButton();
        tc10 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        transferencia = new javax.swing.JRadioButton();
        retiro = new javax.swing.JRadioButton();
        consultarSaldo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(tdestandar);
        tdestandar.setText("Tarjeta Estandar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Realizar Operacion");

        destinoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Operacion");

        buttonGroup2.add(coro);
        coro.setText("Cuenta Oro");
        coro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coroActionPerformed(evt);
            }
        });

        jLabel2.setText("Cuenta destino");

        buttonGroup2.add(cestandar);
        cestandar.setText("Cuenta Estandar");

        jLabel3.setText("Cantidad");

        transButton.setText("Realizar operacion");
        transButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Débito");

        jLabel4.setText("Tipo de cuenta destino");

        buttonGroup1.add(tdjoven);
        tdjoven.setText("Tarjeta joven");
        tdjoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdjovenActionPerformed(evt);
            }
        });

        buttonGroup2.add(cjoven);
        cjoven.setText("Cuenta Joven");

        buttonGroup1.add(td10);
        td10.setText("Tarjeta 10");

        buttonGroup2.add(c10);
        c10.setText("Cuenta 10");

        buttonGroup1.add(tdoro);
        tdoro.setText("Tarjeta Oro");

        buttonGroup1.add(tcoro);
        tcoro.setText("Tarjeta Oro");

        buttonGroup1.add(tc10);
        tc10.setText("Tarjeta 10");

        jLabel7.setText("Credito");

        jLabel5.setText("Tipo de tarjeta origen");

        buttonGroup3.add(transferencia);
        transferencia.setText("Transferencia");

        buttonGroup3.add(retiro);
        retiro.setText("Retiro");
        retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiroActionPerformed(evt);
            }
        });

        buttonGroup3.add(consultarSaldo);
        consultarSaldo.setText("Consultar Saldo");
        consultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retiro)
                            .addComponent(transferencia)
                            .addComponent(consultarSaldo)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destinoField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(cantidadField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cestandar)
                        .addComponent(c10)
                        .addComponent(cjoven)
                        .addComponent(coro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(22, 22, 22))
                            .addComponent(tdoro)
                            .addComponent(tdestandar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tdjoven)
                                    .addComponent(td10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tcoro)
                                    .addComponent(tc10))))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(transButton)
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tdjoven)
                            .addComponent(tc10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(td10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tcoro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tdoro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tdestandar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(transferencia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(retiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(consultarSaldo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(destinoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(cjoven)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cestandar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(transButton)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destinoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoFieldActionPerformed

    private void coroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coroActionPerformed

    private void transButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transButtonActionPerformed
        String destino = "";
        float cantidad;
        String operacion = "";
        if(retiro.isSelected()){
            operacion = "retiro";
        }else if(transferencia.isSelected()){
            operacion = "transferencia";
        }else if(consultarSaldo.isSelected()){
            operacion="consultarsaldo";
        }
        destino = destinoField.getText();
        cantidad = Float.parseFloat(cantidadField.getText());
        Cuenta cuenta = null;

        if (cjoven.isSelected()) {
            cuenta = new CuentaJoven();
        } else if (c10.isSelected()) {
            cuenta = new Cuenta10();
        } else if (coro.isSelected()) {
            cuenta = new CuentaOro();
        } else if (cestandar.isSelected()) {
            cuenta = new CuentaEstandar();
        }

        int flag = 0;
        TarjetaDebito tarjetaD = null;
        TarjetaCredito tarjetaC = null;
        if (tdjoven.isSelected()) {
            tarjetaD = new TarjetaDebitoJoven();
            flag = 1;
        } else if (td10.isSelected()) {
            tarjetaD = new TarjetaDebito10();
            flag = 1;
        } else if (tdoro.isSelected()) {
            tarjetaD = new TarjetaDebitoOro();
            flag = 1;
        } else if (tdestandar.isSelected()) {
            tarjetaD = new TarjetaDebitoEstandar();
            flag = 1;
        } else if (tc10.isSelected()) {
            tarjetaC = new TarjetaCredito10();
            flag = 2;
        } else if (tcoro.isSelected()) {
            tarjetaC = new TarjetaCreditoOro();
            flag = 2;
        }
        MiFachada fachada = new MiFachada();
        fachada.llamar(cantidad, destino, operacion, flag, cuenta, tarjetaD, tarjetaC);
    }//GEN-LAST:event_transButtonActionPerformed

    private void tdjovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdjovenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdjovenActionPerformed

    private void consultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarSaldoActionPerformed

    private void retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problema2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton c10;
    private javax.swing.JTextField cantidadField;
    private javax.swing.JRadioButton cestandar;
    private javax.swing.JRadioButton cjoven;
    private javax.swing.JRadioButton consultarSaldo;
    private javax.swing.JRadioButton coro;
    private javax.swing.JTextField destinoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton retiro;
    private javax.swing.JRadioButton tc10;
    private javax.swing.JRadioButton tcoro;
    private javax.swing.JRadioButton td10;
    private javax.swing.JRadioButton tdestandar;
    private javax.swing.JRadioButton tdjoven;
    private javax.swing.JRadioButton tdoro;
    private javax.swing.JButton transButton;
    private javax.swing.JRadioButton transferencia;
    // End of variables declaration//GEN-END:variables
}
